### ISSUE TITLE
Pomodoro Timer ticking down even in break.

### ISSUE THREAD

**Issue by ghost** [lovac42/LifeDrain_EndGames#4]
Hello
The pomodoro bar ticks down even in the take a break phase.

Version 2.1.20 (1fbd925f)
Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Windows 10

**Comment by lovac42** [comment]
It's supposed to. -10 means you've exceeded the time limit by 10 secs.

**Comment by ghost** [comment]
I'm sorry for not being clear, I mean the life drain bar
![2020-02-13_17-31-53](https://user-images.githubusercontent.com/13769570/74435663-da9e8100-4e5c-11ea-8cf9-6dcbdf554f17.gif)

**Comment by lovac42** [comment]
I'm not able to reproduce this with the latest version of anki 2.1.20 released this morning and the latest version of LifeDrain, plus this addon. Tested with various configs. Perhaps if you could narrow this down as to what maybe triggering this?

**Comment by ghost** [comment]
Turned out to be a conflict with [Keep card displayed in reviewer until it is modified](https://ankiweb.net/shared/info/1894745652)

**Comment by lovac42** [comment]
Naturally there would be a price to pay for using such an addon.

Pinging @Arthur-Milchior to see if you're interested in this. Since the point of said addon was to prevent resetState during note edits, maybe put in a test to see who the calling function was if it's not invoked by note editor, bypass the addon?

**Comment by Arthur-Milchior** [comment]
Thank you for letting me know. Didnt expect this addon to create any trouble. Very simple addon. I dont know what pomodoro does. Ill need to take a look later

**Comment by lovac42** [comment]
Sure thing. Something simple like DoubleThink should fix it.
https://github.com/lovac42/Doublethink/blob/master/src/doublethink/main.py
